version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    environment:
      - JAEGER_REPORTER_LOG_SPANS=true
#    networks:
#      - jaeger-example

  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "4317:4317"
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"
#    networks:
#      - jaeger-example
    depends_on:
      - jaeger

#networks:
#  jaeger-example: